[package]
name = "buklo"
version = "0.1.9"
description = "Buklo is a simple CLI HTTP client"
keywords = ["cli"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ghishadow/buklo"
documentation = "https://docs.rs/crate/buklo"
edition = "2021"
rust-version = "1.60"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive", "cargo", "env", "unicode", "wrap_help"] }
env_logger = "0.9.0"
log = "0.4.17"
owo-colors = "3.4.0"
serde = "1.0.137"

update-informer = "0.5.0" 
ureq = { version = "2.4.0", features = ["json", "charset"] }
url = "2.2.2"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
codegen-units = 1
lto = true
opt-level = "s" # Optimize for size
strip = "debuginfo"
