[package]
name = "buklo"
version = "0.1.0"
edition = "2021"
description = "Buklo is a simple HTTP client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "*", features = ["json", "charset"] }
clap = { version = "3.0.14", features = ["derive"] }
update-informer = "0.2.0"
colored = "2"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false