[package]
name = "buklo"
version = "0.1.0"
description = "Buklo is a simple CLI HTTP client"
keywords = ["cli"]
license = "MIT"
repository = "https://github.com/ghishadow/bulko"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]

ureq = { version = "2.4.0", features = ["json", "charset"] }
clap = { version = "3.0.14", features = ["derive"] }
update-informer = "0.2.0"
colored = "2"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
codegen-units = 1
lto = true