[package]
name = "buklo"
version = "0.1.11"
description = "Buklo is a simple CLI HTTP client"
keywords = ["cli"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ghishadow/buklo"
documentation = "https://docs.rs/crate/buklo"
edition = "2021"
rust-version = "1.64"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
ureq = { version = "2.5.0", default-features = false, features = ["gzip", "json", "socks-proxy", "native-certs"] }
clap = { version = "4", features = ["derive", "cargo", "color", "env", "unicode", "wrap_help"] } 
serde = "1.0.144"
update-informer = "0.5.0" 
owo-colors = "3.5.0"
log = "0.4.17"
env_logger = "0.9.0"
url = "2.2.2"
mimalloc = "0.1.29" 

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
codegen-units = 1
lto = true
opt-level = "s" # Optimize for size
strip = "debuginfo"
panic = "abort"
