[toolchain]
components = ["rustfmt", "rust-src", "clippy"]
profile = "minimal"
channel = "nightly"
targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl", "wasm32-wasi", "riscv64gc-unknown-linux-gnu"]

