[toolchain]
components = ["rustfmt", "rust-src", "clippy"]
profile = "minimal"
targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl", "wasm32-unknown-unknown", "wasm32-wasi", "riscv64gc-unknown-linux-gnu"] 
