on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

name: Pull request checks

jobs:
  check:
    name: Rust (${{ matrix.toolchain }}) on ${{ matrix.os }}
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        toolchain: [ stable ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install build-essential

      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}

      - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6

      - name: Setup Mold
        uses: rui314/setup-mold@v1
        with:
          mold-version: 1.4.1
          make-default: false

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
      - run: rustup component add rustfmt
      - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6

      - name: Setup Mold
        uses: rui314/setup-mold@v1
        with:
          mold-version: 1.4.1
          make-default: false
      
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable
      - run: rustup component add clippy
      - name: Install dependencies on Ubuntu
        run: sudo apt-get update && sudo apt-get build-essential
      - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6

      - name: Setup Mold
        uses: rui314/setup-mold@v1
        with:
          mold-version: 1.4.1
          make-default: false
  
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
